env:
  es2021: true
  node: true
extends:
  - standard
  - plugin:@typescript-eslint/recommended
  - prettier
  - plugin:unicorn/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
rules:
  'unicorn/prevent-abbreviations': off
  'unicorn/no-array-reduce': off
  'unicorn/prefer-top-level-await': off
  'unicorn/number-literal-case': off
